x-env_file:
  &env-file
  env_file:
    - ../.env

version: '3.5'

services:
  editor:
    build: editor
    init: true

  discord-proxy:
    <<: *env-file
    build:
      context: ..
      target: discord-proxy

  discord-gateway:
    <<: *env-file
    build:
      context: ..
      target: discord-gateway

  rabbitmq:
    <<: *env-file
    build: ../infra/rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672

  postgres:
    build: ../infra/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blargbot
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  cassandra:
    build: ../infra/cassandra
    environment:
      CASSANDRA_KEYSPACE: blargbot
      CASSANDRA_USER: blargbot
      CASSANDRA_PASSWORD: BlargPass123
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 7199:7199
      - 9160:9160
    volumes:
      - cassandra:/var/lib/cassandra

  rethinkdb:
    build: ../infra/rethinkdb
    environment:
      RETHINKDB_DATABASE: blargbot
      RETHINKDB_USERNAME: blargbot
      RETHINKDB_PASSWORD: BlargPass123
    ports:
      - 29015:29015
      - 28015:28015
      - 29016:8080
    volumes:
      - rethink:/data

volumes:
  rabbitmq:
  rethink:
  cassandra:
  postgres:
